# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Curing the Curse of Knowledge
title: Curing the Curse of Knowledge
email: course@curingthecurse.com
description: Lessons on clear writing.

url: https://curingthecurse.com

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
twitter_username: curingthecurse_

show_social_icons: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jemoji
